# Generated by Django 5.2.15 on 2026-08-12 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_location_scene_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='traits',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='project',
            name='character_traits',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
