# Generated by Django 5.2.15 on 2026-07-19 06:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_dialogue_graph'),
    ]

    operations = [
        migrations.AddField(
            model_name='level',
            name='intro_scene',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='intro_for_levels', to='api.scene'),
        ),
        migrations.AddField(
            model_name='level',
            name='layout',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.CreateModel(
            name='EntityType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('glyph', models.CharField(max_length=1)),
                ('category', models.CharField(choices=[('enemy', 'Enemy'), ('hazard', 'Hazard'), ('pickup', 'Pickup'), ('prop', 'Prop')], default='enemy', max_length=10)),
                ('description', models.TextField(blank=True, default='')),
                ('behavior', models.JSONField(blank=True, default=dict)),
                ('image_key', models.CharField(blank=True, default='', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entity_types', to='api.project')),
            ],
            options={
                'ordering': ['name', 'id'],
                'constraints': [models.UniqueConstraint(fields=('project', 'glyph'), name='uniq_entity_glyph'), models.UniqueConstraint(fields=('project', 'name'), name='uniq_entity_name')],
            },
        ),
    ]
