# Generated by Django 5.2.15 on 2026-08-13 03:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_character_traits'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='image_key',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='location',
            name='kind',
            field=models.CharField(blank=True, choices=[('interior', 'Interior'), ('exterior', 'Exterior')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='location',
            name='mood',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='location',
            name='props',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='location',
            name='scale',
            field=models.CharField(blank=True, choices=[('cramped', 'Cramped'), ('room', 'Room'), ('open', 'Open'), ('vast', 'Vast')], default='', max_length=20),
        ),
        migrations.CreateModel(
            name='LocationConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(blank=True, default='', max_length=100)),
                ('bidirectional', models.BooleanField(default=True)),
                ('requirements', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('from_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connections_out', to='api.location')),
                ('to_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connections_in', to='api.location')),
            ],
            options={
                'ordering': ['id'],
                'constraints': [models.UniqueConstraint(fields=('from_location', 'to_location'), name='uniq_location_connection')],
            },
        ),
    ]
