# Generated by Django 5.2.15 on 2026-08-13 04:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_location_image_key_location_kind_location_mood_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='New Ability', max_length=100)),
                ('description', models.TextField(blank=True, default='')),
                ('params', models.JSONField(blank=True, default=dict)),
                ('unlock_requirements', models.JSONField(blank=True, default=list)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='abilities', to='api.project')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
    ]
