# Generated by Django 5.2.15 on 2026-08-25 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_level_intro_scene_level_layout_entitytype'),
        ('api', '0019_ability'),
    ]

    operations = [
    ]
