# Generated by Django 5.2.15 on 2026-08-25 22:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_merge_20260825_2045'),
    ]

    operations = [
        migrations.CreateModel(
            name='DesignAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_type', models.CharField(max_length=20)),
                ('object_id', models.PositiveIntegerField()),
                ('slug', models.CharField(max_length=120)),
                ('is_current', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='api.project')),
            ],
            options={
                'indexes': [models.Index(fields=['project', 'object_type', 'object_id', 'is_current'], name='api_designa_project_f99cfd_idx'), models.Index(fields=['project', 'object_type', 'slug'], name='api_designa_project_e28a96_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_current', True)), fields=('project', 'object_type', 'slug'), name='uniq_current_design_address')],
            },
        ),
    ]
