# Generated by Django 5.2.15 on 2026-08-25 22:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_designaddress'),
    ]

    operations = [
        migrations.CreateModel(
            name='BuildRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('engine', models.CharField(default='godot', max_length=30)),
                ('address', models.CharField(max_length=200)),
                ('object_type', models.CharField(max_length=20)),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('engine_path', models.CharField(blank=True, default='', max_length=500)),
                ('built_hash', models.CharField(blank=True, default='', max_length=64)),
                ('status', models.CharField(choices=[('in_progress', 'In progress'), ('built', 'Built'), ('verified', 'Verified')], default='built', max_length=20)),
                ('note', models.TextField(blank=True, default='')),
                ('reported_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='build_records', to='api.project')),
            ],
            options={
                'ordering': ['address'],
                'indexes': [models.Index(fields=['project', 'engine', 'object_type', 'object_id'], name='api_buildre_project_53b6ae_idx')],
                'constraints': [models.UniqueConstraint(fields=('project', 'engine', 'address'), name='uniq_build_record_address')],
            },
        ),
    ]
