# Generated by Django 5.2.15 on 2026-08-31 19:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_buildrecord'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deviation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('engine', models.CharField(default='godot', max_length=30)),
                ('address', models.CharField(max_length=250)),
                ('base_address', models.CharField(max_length=200)),
                ('field', models.CharField(blank=True, default='', max_length=120)),
                ('object_type', models.CharField(max_length=20)),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('kind', models.CharField(choices=[('conflict', 'Contradicts the design'), ('gap', 'Design was silent')], max_length=20)),
                ('design_value', models.JSONField(blank=True, null=True)),
                ('build_value', models.JSONField(blank=True, null=True)),
                ('design_hash', models.CharField(blank=True, default='', max_length=64)),
                ('engine_path', models.CharField(blank=True, default='', max_length=500)),
                ('note', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted into design'), ('rejected', 'Rejected — rework the build')], default='pending', max_length=20)),
                ('applied', models.BooleanField(default=False)),
                ('resolution_note', models.TextField(blank=True, default='')),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('reported_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deviations', to='api.project')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['project', 'status'], name='api_deviati_project_6eb20f_idx'), models.Index(fields=['project', 'engine', 'base_address'], name='api_deviati_project_172484_idx')],
                'constraints': [models.UniqueConstraint(fields=('project', 'engine', 'address'), name='uniq_deviation_address')],
            },
        ),
    ]
