# Generated by Django 5.2.15 on 2026-08-31 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_deviation'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='extent',
            field=models.CharField(blank=True, choices=[('level', 'The whole level'), ('area', 'An area within the level'), ('point', 'A single spot')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='location',
            name='region',
            field=models.JSONField(blank=True, default=None, null=True),
        ),
    ]
