# Generated by Django 5.2.15 on 2026-08-31 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_location_extent_location_region'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='sprite',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='entitytype',
            name='sprite',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
