# Generated by Django 5.2.15 on 2026-08-31 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_character_sprite_entitytype_sprite'),
    ]

    operations = [
        migrations.AddField(
            model_name='ability',
            name='image_key',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='level',
            name='image_key',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='project',
            name='image_key',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
    ]
