# Generated by Django 5.2.15 on 2026-08-31 21:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_ability_image_key_level_image_key_project_image_key'),
    ]

    operations = [
        migrations.CreateModel(
            name='TileType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('glyph', models.CharField(max_length=1)),
                ('collision', models.CharField(choices=[('solid', 'Solid — blocks from every side'), ('none', 'Passable — no collision'), ('one_way', 'One-way — land on top, jump up through')], default='solid', max_length=10)),
                ('behavior', models.JSONField(blank=True, default=dict)),
                ('description', models.TextField(blank=True, default='')),
                ('color', models.CharField(blank=True, default='', max_length=9)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tile_types', to='api.project')),
            ],
            options={
                'ordering': ['order', 'name', 'id'],
                'constraints': [models.UniqueConstraint(fields=('project', 'glyph'), name='uniq_tile_glyph'), models.UniqueConstraint(fields=('project', 'name'), name='uniq_tile_name')],
            },
        ),
    ]
