/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/auth": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Authenticate the user (placeholder)
         * @description Placeholder for future authentication.
         *
         *     Always returns HTTP 400 and is intentionally NOT called by the frontend yet.
         */
        post: operations["api_api_auth"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/user": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get the current user */
        get: operations["api_api_get_current_user"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update the current user */
        patch: operations["api_api_update_current_user"];
        trace?: never;
    };
    "/api/characters": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List characters
         * @description All characters, or just one project's characters when `project_id` is given.
         */
        get: operations["api_api_list_characters"];
        put?: never;
        /** Create a character */
        post: operations["api_api_create_character"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/characters/{character_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a character */
        get: operations["api_api_get_character"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update a character */
        patch: operations["api_api_update_character"];
        trace?: never;
    };
    "/api/characters/{character_id}/relationships": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Add or update a relationship
         * @description Directed: creates an edge from this character to `other_id`. Shows only on this
         *     character's page. If the same directed edge already exists, its label is updated.
         */
        post: operations["api_api_add_relationship"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/characters/{character_id}/relationships/{relationship_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Remove a relationship */
        delete: operations["api_api_delete_relationship"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/characters/{character_id}/image": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Upload a character portrait
         * @description Upload an image file for the character; stores it in S3 and saves the public URL.
         */
        post: operations["api_api_upload_character_image"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/characters/{character_id}/generate-image": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Generate a character portrait with AI
         * @description Generate a portrait with FLUX (fal.ai), upload it to S3, and save the key on the character.
         */
        post: operations["api_api_generate_character_image"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/entities": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List entity types */
        get: operations["api_api_list_entity_types"];
        put?: never;
        /** Create an entity type */
        post: operations["api_api_create_entity_type"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/entities/{entity_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete an entity type */
        delete: operations["api_api_delete_entity_type"];
        options?: never;
        head?: never;
        /** Update an entity type */
        patch: operations["api_api_update_entity_type"];
        trace?: never;
    };
    "/api/entities/{entity_id}/image": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Upload an entity sprite/concept image */
        post: operations["api_api_upload_entity_image"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/entities/{entity_id}/generate-image": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Generate an entity image with AI */
        post: operations["api_api_generate_entity_image"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{project_id}/seed-entities": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Add the starter platformer palette
         * @description Create the starter entity set (walker enemy, spikes, coin) for a project, skipping
         *     any whose glyph or name is already taken. Returns the project's full palette.
         */
        post: operations["api_api_seed_entities"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List projects */
        get: operations["api_api_list_projects"];
        put?: never;
        /** Create a project */
        post: operations["api_api_create_project"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{project_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a project */
        get: operations["api_api_get_project"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Update a project
         * @description Partial update: rename, Settings (dimension/genre), Systems, or Preview (hud_layout).
         */
        patch: operations["api_api_update_project"];
        trace?: never;
    };
    "/api/projects/{project_id}/export": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Export the project as a gameblueprint document
         * @description The unified source-of-truth export (`gameblueprint/0.1`): systems + derived feel
         *     numbers, characters, entity palette, tile legend, and every level's layout grid,
         *     entity coordinates, transitions, and dialogue graphs. This is the document the MCP
         *     server and any engine codegen consume — schema contract in docs/blueprint-schema.md.
         */
        get: operations["api_api_export_project"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/abilities": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List abilities
         * @description All abilities, or just one project's when `project_id` is given — the verb set.
         */
        get: operations["api_api_list_abilities"];
        put?: never;
        /**
         * Create an ability
         * @description Add a verb to the project. `unlock_requirements` uses the same bounded vocabulary as
         *     dialogue requirements; empty means the player has it from the start.
         */
        post: operations["api_api_create_ability"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/abilities/{ability_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Delete an ability
         * @description Plain delete — nothing references an `Ability` yet (progression rewards will, once
         *     they exist), so there is nothing to 409 on.
         */
        delete: operations["api_api_delete_ability"];
        options?: never;
        head?: never;
        /**
         * Update an ability
         * @description Partial update — `params`/`unlock_requirements` replace the whole value when given.
         */
        patch: operations["api_api_update_ability"];
        trace?: never;
    };
    "/api/levels": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List levels
         * @description All levels, or just one project's levels when `project_id` is given.
         */
        get: operations["api_api_list_levels"];
        put?: never;
        /** Create a level */
        post: operations["api_api_create_level"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/levels/{level_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a level */
        get: operations["api_api_get_level"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update a level */
        patch: operations["api_api_update_level"];
        trace?: never;
    };
    "/api/levels/{level_id}/characters": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Characters in a level (deduced from dialogue)
         * @description The level's cast, deduced from which characters speak its dialogue, each with the
         *     lines they speak (across the level's scenes). Ordered by character name.
         */
        get: operations["api_api_level_characters"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/scenes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List scenes */
        get: operations["api_api_list_scenes"];
        put?: never;
        /**
         * Create a scene
         * @description Create a scene in a level (optionally at a location). Order auto-appends within the level.
         */
        post: operations["api_api_create_scene"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/scenes/{scene_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Update a scene
         * @description Partial update: rename, (re)assign to a location, or reorder.
         */
        patch: operations["api_api_update_scene"];
        trace?: never;
    };
    "/api/locations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List locations
         * @description All locations, or just one level's locations when `level_id` is given. Each row
         *     carries its detail fields, cast, and connections (its exits).
         */
        get: operations["api_api_list_locations"];
        put?: never;
        /** Create a location */
        post: operations["api_api_create_location"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/locations/{location_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a location */
        get: operations["api_api_get_location"];
        put?: never;
        post?: never;
        /** Delete a location */
        delete: operations["api_api_delete_location"];
        options?: never;
        head?: never;
        /**
         * Update a location
         * @description Partial update: name/description/order plus the detail fields (kind, scale, mood, props).
         */
        patch: operations["api_api_update_location"];
        trace?: never;
    };
    "/api/locations/{location_id}/characters": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Place a character at a location */
        post: operations["api_api_add_location_character"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/locations/{location_id}/characters/{character_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Remove a character from a location */
        delete: operations["api_api_remove_location_character"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/locations/{location_id}/connections": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Connect a location to another
         * @description Add a labeled way from this location to another one *in the same level* — the
         *     world graph's edge. `bidirectional` (default) means it's walkable both ways, so it
         *     also shows on the far location. `requirements` locks the passage using the same
         *     vocabulary as dialogue requirements (e.g. `has_item` + `item_cellar_key`).
         *     Re-connecting the same ordered pair updates that connection instead of duplicating it.
         */
        post: operations["api_api_add_location_connection"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/locations/{location_id}/connections/{connection_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Remove a connection
         * @description Delete a connection from either end — the id comes from the location row's
         *     `connections`, which includes bidirectional edges authored from the other side.
         */
        delete: operations["api_api_delete_location_connection"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/locations/{location_id}/image": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Upload a location reference image
         * @description Upload a reference image for the location; stores it in S3 and saves the key.
         */
        post: operations["api_api_upload_location_image"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/locations/{location_id}/generate-image": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Generate a location reference image with AI
         * @description Generate reference art with FLUX (fal.ai), upload it to S3, and save the key.
         *
         *     Omit `prompt` to build one from the location's name, description, and mood/kind/scale.
         */
        post: operations["api_api_generate_location_image"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/scenes/{scene_id}/dialogues": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * All dialogue nodes in a scene (flat, for the tree view)
         * @description Every dialogue node in a scene as a flat list — the frontend builds the graph from
         *     `id`/`parent_ids`. One JOIN (no N+1); each node's character serializes like everywhere else
         *     (presigned image URL via CharacterOut).
         */
        get: operations["api_api_scene_dialogue_tree"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/dialogues": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List root dialogues
         * @description Root dialogues (no incoming edges). Pass `scene_id` to get the roots for one scene.
         */
        get: operations["api_api_list_root_dialogues"];
        put?: never;
        /**
         * Create a dialogue
         * @description Create a dialogue node. Pass `parent_id` to attach it as a response of another node.
         */
        post: operations["api_api_create_dialogue"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/dialogues/{dialogue_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get a dialogue
         * @description A dialogue with its character, immediate responses, and linking parent(s).
         */
        get: operations["api_api_get_dialogue"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Update a dialogue
         * @description Partial update: only the fields present in the request body are changed.
         */
        patch: operations["api_api_update_dialogue"];
        trace?: never;
    };
    "/api/dialogues/{dialogue_id}/link": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Link an existing node as a response (reuse/reconverge)
         * @description Attach an existing node (`target_id`) as an additional response of `dialogue_id`,
         *     without creating a new node — how two branches converge back onto the same node.
         */
        post: operations["api_api_link_dialogue"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/scenes/{scene_id}/import-yarn": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Import a Yarn script into a scene as dialogue nodes
         * @description Parse a bounded subset of Yarn (see `services/yarn_import.py`) and materialize it as
         *     dialogue nodes/edges in this scene. Pass `parent_id` to attach the pasted content as a new
         *     response of that existing node instead of a freestanding root — continuing a branch that's
         *     already there. All-or-nothing: a bad jump target aborts the whole import rather than
         *     leaving orphaned nodes.
         */
        post: operations["api_api_import_yarn_view"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/scenes/{scene_id}/export-yarn": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Export a scene's dialogue graph as a Yarn script */
        get: operations["api_api_export_yarn_view"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Error */
        Error: {
            /** Error */
            error: string;
        };
        /** UserOut */
        UserOut: {
            /** Id */
            id: number;
            /** Name */
            name: string;
            /** Theme */
            theme: string;
        };
        /**
         * UserUpdateIn
         * @description Partial update of the current user (e.g. their selected theme).
         */
        UserUpdateIn: {
            /** Name */
            name?: string | null;
            /** Theme */
            theme?: string | null;
        };
        /** CharacterOut */
        CharacterOut: {
            /** Id */
            id: number;
            /** Name */
            name: string;
            /**
             * Description
             * @default
             */
            description: string;
            /**
             * Image Url
             * @default
             */
            image_url: string;
        };
        /** CharacterCreateIn */
        CharacterCreateIn: {
            /**
             * Name
             * @default New Character
             */
            name: string;
            /**
             * Description
             * @default
             */
            description: string;
            /** Project Id */
            project_id?: number | null;
        };
        /**
         * CharacterDetailOut
         * @description A single character with its description, portrait, and relationships.
         */
        CharacterDetailOut: {
            /** Id */
            id: number;
            /** Name */
            name: string;
            /**
             * Description
             * @default
             */
            description: string;
            /**
             * Image Url
             * @default
             */
            image_url: string;
            /**
             * Image Key
             * @default
             */
            image_key: string;
            /** Project Id */
            project_id?: number | null;
            /**
             * Related
             * @default []
             */
            related: components["schemas"]["RelatedCharacterOut"][];
            /**
             * Traits
             * @default {}
             */
            traits: {
                [key: string]: unknown;
            };
        };
        /**
         * RelatedCharacterOut
         * @description A character related to another, plus the relationship's label and edge id.
         */
        RelatedCharacterOut: {
            /** Relationship Id */
            relationship_id: number;
            /** Id */
            id: number;
            /** Name */
            name: string;
            /** Relationship */
            relationship: string;
        };
        /**
         * CharacterUpdateIn
         * @description Partial update — omitted fields are left unchanged.
         */
        CharacterUpdateIn: {
            /** Name */
            name?: string | null;
            /** Description */
            description?: string | null;
            /** Traits */
            traits?: {
                [key: string]: unknown;
            } | null;
        };
        /** RelationshipCreateIn */
        RelationshipCreateIn: {
            /** Other Id */
            other_id: number;
            /**
             * Relationship
             * @default
             */
            relationship: string;
        };
        /** GenerateImageIn */
        GenerateImageIn: {
            /** Prompt */
            prompt?: string | null;
        };
        /**
         * EntityTypeOut
         * @description A placeable non-character thing (enemy/hazard/pickup/prop) in a project's palette.
         */
        EntityTypeOut: {
            /** Id */
            id: number;
            /** Name */
            name: string;
            /** Glyph */
            glyph: string;
            /** Category */
            category: string;
            /**
             * Description
             * @default
             */
            description: string;
            /**
             * Behavior
             * @default {}
             */
            behavior: {
                [key: string]: unknown;
            };
            /** Project Id */
            project_id: number;
            /**
             * Image Url
             * @default
             */
            image_url: string;
        };
        /** EntityTypeCreateIn */
        EntityTypeCreateIn: {
            /** Project Id */
            project_id: number;
            /** Name */
            name: string;
            /** Glyph */
            glyph: string;
            /**
             * Category
             * @default enemy
             */
            category: string;
            /**
             * Description
             * @default
             */
            description: string;
            /**
             * Behavior
             * @default {}
             */
            behavior: {
                [key: string]: unknown;
            };
        };
        /**
         * EntityTypeUpdateIn
         * @description Partial update — omitted fields are left unchanged.
         */
        EntityTypeUpdateIn: {
            /** Name */
            name?: string | null;
            /** Glyph */
            glyph?: string | null;
            /** Category */
            category?: string | null;
            /** Description */
            description?: string | null;
            /** Behavior */
            behavior?: {
                [key: string]: unknown;
            } | null;
        };
        /**
         * ProjectOut
         * @description A game project plus its game-wide config (settings/systems/HUD).
         */
        ProjectOut: {
            /** Id */
            id: number;
            /** Name */
            name: string;
            /** Order */
            order: number;
            /** Dimension */
            dimension: string;
            /** Genre */
            genre: string;
            /**
             * Systems
             * @default {}
             */
            systems: {
                [key: string]: unknown;
            };
            /**
             * Hud Layout
             * @default {}
             */
            hud_layout: {
                [key: string]: unknown;
            };
            /**
             * State Schema
             * @default {}
             */
            state_schema: {
                [key: string]: unknown;
            };
            /**
             * Character Traits
             * @default []
             */
            character_traits: {
                [key: string]: unknown;
            }[];
        };
        /** ProjectCreateIn */
        ProjectCreateIn: {
            /**
             * Name
             * @default New Project
             */
            name: string;
            /** Order */
            order?: number | null;
        };
        /**
         * ProjectUpdateIn
         * @description Partial update — omitted fields are left unchanged. One PATCH serves rename,
         *     Settings (dimension/genre), Systems, and Preview (hud_layout) saves.
         */
        ProjectUpdateIn: {
            /** Name */
            name?: string | null;
            /** Order */
            order?: number | null;
            /** Dimension */
            dimension?: string | null;
            /** Genre */
            genre?: string | null;
            /** Systems */
            systems?: {
                [key: string]: unknown;
            } | null;
            /** Hud Layout */
            hud_layout?: {
                [key: string]: unknown;
            } | null;
            /** State Schema */
            state_schema?: {
                [key: string]: unknown;
            } | null;
            /** Character Traits */
            character_traits?: {
                [key: string]: unknown;
            }[] | null;
        };
        /**
         * AbilityOut
         * @description A player verb: what it is, the knobs that tune it, and what unlocks it.
         */
        AbilityOut: {
            /** Id */
            id: number;
            /** Project Id */
            project_id?: number | null;
            /** Name */
            name: string;
            /**
             * Description
             * @default
             */
            description: string;
            /**
             * Params
             * @default {}
             */
            params: {
                [key: string]: unknown;
            };
            /**
             * Unlock Requirements
             * @default []
             */
            unlock_requirements: {
                [key: string]: unknown;
            }[];
            /** Order */
            order: number;
        };
        /** AbilityCreateIn */
        AbilityCreateIn: {
            /** Project Id */
            project_id?: number | null;
            /**
             * Name
             * @default New Ability
             */
            name: string;
            /**
             * Description
             * @default
             */
            description: string;
            /**
             * Params
             * @default {}
             */
            params: {
                [key: string]: unknown;
            };
            /**
             * Unlock Requirements
             * @default []
             */
            unlock_requirements: {
                [key: string]: unknown;
            }[];
            /** Order */
            order?: number | null;
        };
        /**
         * AbilityUpdateIn
         * @description Partial update — omitted fields are left unchanged; `params` and
         *     `unlock_requirements` replace the whole value when given.
         */
        AbilityUpdateIn: {
            /** Name */
            name?: string | null;
            /** Description */
            description?: string | null;
            /** Params */
            params?: {
                [key: string]: unknown;
            } | null;
            /** Unlock Requirements */
            unlock_requirements?: {
                [key: string]: unknown;
            }[] | null;
            /** Order */
            order?: number | null;
        };
        /** LevelOut */
        LevelOut: {
            /** Id */
            id: number;
            /** Name */
            name: string;
            /** Order */
            order: number;
            /** Project Id */
            project_id?: number | null;
            /**
             * Layout
             * @default {}
             */
            layout: {
                [key: string]: unknown;
            };
            /** Intro Scene Id */
            intro_scene_id?: number | null;
        };
        /** LevelCreateIn */
        LevelCreateIn: {
            /**
             * Name
             * @default New Level
             */
            name: string;
            /** Order */
            order?: number | null;
            /** Project Id */
            project_id?: number | null;
        };
        /**
         * LevelUpdateIn
         * @description Partial update of a level (rename, layout grid, intro dialogue scene).
         */
        LevelUpdateIn: {
            /** Name */
            name?: string | null;
            /** Order */
            order?: number | null;
            /** Layout */
            layout?: {
                [key: string]: unknown;
            } | null;
            /** Intro Scene Id */
            intro_scene_id?: number | null;
        };
        /** LevelCharacterLineOut */
        LevelCharacterLineOut: {
            /** Id */
            id: number;
            /** Text */
            text: string;
            /** Scene Id */
            scene_id?: number | null;
            /**
             * Scene Name
             * @default
             */
            scene_name: string;
        };
        /**
         * LevelCharacterOut
         * @description A character appearing in a level (deduced from dialogue), with the lines they speak.
         */
        LevelCharacterOut: {
            /** Id */
            id: number;
            /** Name */
            name: string;
            /**
             * Description
             * @default
             */
            description: string;
            /**
             * Image Url
             * @default
             */
            image_url: string;
            /**
             * Lines
             * @default []
             */
            lines: components["schemas"]["LevelCharacterLineOut"][];
        };
        /** SceneOut */
        SceneOut: {
            /** Id */
            id: number;
            /** Name */
            name: string;
            /** Level Id */
            level_id: number;
            /** Level Name */
            level_name: string;
            /** Location Id */
            location_id?: number | null;
        };
        /** SceneCreateIn */
        SceneCreateIn: {
            /**
             * Name
             * @default New Scene
             */
            name: string;
            /** Level Id */
            level_id: number;
            /** Location Id */
            location_id?: number | null;
            /** Order */
            order?: number | null;
        };
        /**
         * SceneUpdateIn
         * @description Partial update — omitted fields are left unchanged.
         */
        SceneUpdateIn: {
            /** Name */
            name?: string | null;
            /** Location Id */
            location_id?: number | null;
            /** Order */
            order?: number | null;
        };
        /**
         * LocationConnectionOut
         * @description A way out of the location whose row this appears on, described *relative to it*:
         *     `other_id`/`other_name` is the place at the far end and `direction` says which way the
         *     edge was authored ("out" = from this location; "in" = a bidirectional connection
         *     authored from the other side, so it's still walkable from here).
         */
        LocationConnectionOut: {
            /** Id */
            id: number;
            /** From Location Id */
            from_location_id: number;
            /** To Location Id */
            to_location_id: number;
            /** Other Id */
            other_id: number;
            /** Other Name */
            other_name: string;
            /** Direction */
            direction: string;
            /**
             * Label
             * @default
             */
            label: string;
            /**
             * Bidirectional
             * @default true
             */
            bidirectional: boolean;
            /**
             * Requirements
             * @default []
             */
            requirements: {
                [key: string]: unknown;
            }[];
        };
        /**
         * LocationOut
         * @description A place within a level: its detail fields, reference image, cast, and exits.
         */
        LocationOut: {
            /** Id */
            id: number;
            /** Name */
            name: string;
            /**
             * Description
             * @default
             */
            description: string;
            /** Order */
            order: number;
            /** Level Id */
            level_id: number;
            /**
             * Kind
             * @default
             */
            kind: string;
            /**
             * Scale
             * @default
             */
            scale: string;
            /**
             * Mood
             * @default
             */
            mood: string;
            /**
             * Props
             * @default []
             */
            props: string[];
            /**
             * Image Url
             * @default
             */
            image_url: string;
            /**
             * Image Key
             * @default
             */
            image_key: string;
            /**
             * Characters
             * @default []
             */
            characters: components["schemas"]["CharacterOut"][];
            /**
             * Connections
             * @default []
             */
            connections: components["schemas"]["LocationConnectionOut"][];
        };
        /** LocationCreateIn */
        LocationCreateIn: {
            /**
             * Name
             * @default New Location
             */
            name: string;
            /**
             * Description
             * @default
             */
            description: string;
            /** Order */
            order?: number | null;
            /** Level Id */
            level_id?: number | null;
            /** Kind */
            kind?: string | null;
            /** Scale */
            scale?: string | null;
            /** Mood */
            mood?: string | null;
            /** Props */
            props?: string[] | null;
        };
        /**
         * LocationUpdateIn
         * @description Partial update — omitted fields are left unchanged.
         */
        LocationUpdateIn: {
            /** Name */
            name?: string | null;
            /** Description */
            description?: string | null;
            /** Order */
            order?: number | null;
            /** Kind */
            kind?: string | null;
            /** Scale */
            scale?: string | null;
            /** Mood */
            mood?: string | null;
            /** Props */
            props?: string[] | null;
        };
        /** LocationCharacterIn */
        LocationCharacterIn: {
            /** Character Id */
            character_id: number;
        };
        /**
         * LocationConnectionIn
         * @description Connect this location to another one in the same level.
         */
        LocationConnectionIn: {
            /** To Id */
            to_id: number;
            /**
             * Label
             * @default
             */
            label: string;
            /**
             * Bidirectional
             * @default true
             */
            bidirectional: boolean;
            /**
             * Requirements
             * @default []
             */
            requirements: {
                [key: string]: unknown;
            }[];
        };
        /**
         * DialogueNodeOut
         * @description A single node in a scene's flat dialogue list — enough to lay out the whole graph.
         */
        DialogueNodeOut: {
            /** Id */
            id: number;
            /** Title */
            title: string;
            /**
             * Parent Ids
             * @default []
             */
            parent_ids: number[];
            /** Text */
            text: string;
            character?: components["schemas"]["CharacterOut"] | null;
            /**
             * Requirements
             * @default []
             */
            requirements: {
                [key: string]: unknown;
            }[];
            /**
             * Effects
             * @default []
             */
            effects: {
                [key: string]: unknown;
            }[];
        };
        /**
         * DialogueSummaryOut
         * @description Lightweight dialogue used for root lists and response cards. `option_label` is the
         *     edge's player-facing choice text (falls back to `text` when the edge has none set).
         */
        DialogueSummaryOut: {
            /** Id */
            id: number;
            /** Title */
            title: string;
            /** Text */
            text: string;
            /**
             * Option Label
             * @default
             */
            option_label: string;
            character?: components["schemas"]["CharacterOut"] | null;
            /**
             * Requirements
             * @default []
             */
            requirements: {
                [key: string]: unknown;
            }[];
            /**
             * Effects
             * @default []
             */
            effects: {
                [key: string]: unknown;
            }[];
        };
        /**
         * DialogueDetailOut
         * @description The current dialogue plus its immediate responses (the wheel) and the node(s) that
         *     link to it (0 = scene root, 1 = normal back-nav, 2+ = picker).
         */
        DialogueDetailOut: {
            /** Id */
            id: number;
            /** Title */
            title: string;
            /** Text */
            text: string;
            /** Scene Id */
            scene_id?: number | null;
            /**
             * Parents
             * @default []
             */
            parents: components["schemas"]["DialogueParentOut"][];
            character?: components["schemas"]["CharacterOut"] | null;
            /**
             * Requirements
             * @default []
             */
            requirements: {
                [key: string]: unknown;
            }[];
            /**
             * Effects
             * @default []
             */
            effects: {
                [key: string]: unknown;
            }[];
            /**
             * Responses
             * @default []
             */
            responses: components["schemas"]["DialogueSummaryOut"][];
        };
        /**
         * DialogueParentOut
         * @description A node that links to the current one — powers the back-navigation picker when a
         *     node is reachable from more than one place.
         */
        DialogueParentOut: {
            /** Id */
            id: number;
            /** Title */
            title: string;
            /** Text */
            text: string;
        };
        /**
         * DialogueIn
         * @description Payload to create a dialogue (optionally as a response of `parent_id`).
         */
        DialogueIn: {
            /** Scene Id */
            scene_id?: number | null;
            /** Parent Id */
            parent_id?: number | null;
            /** Character Id */
            character_id?: number | null;
            /**
             * Text
             * @default
             */
            text: string;
            /** Requirements */
            requirements?: {
                [key: string]: unknown;
            }[] | null;
            /** Effects */
            effects?: {
                [key: string]: unknown;
            }[] | null;
        };
        /**
         * DialogueUpdateIn
         * @description Partial update — omitted fields are left unchanged.
         */
        DialogueUpdateIn: {
            /** Character Id */
            character_id?: number | null;
            /** Text */
            text?: string | null;
            /** Requirements */
            requirements?: {
                [key: string]: unknown;
            }[] | null;
            /** Effects */
            effects?: {
                [key: string]: unknown;
            }[] | null;
        };
        /**
         * DialogueLinkIn
         * @description Attach an existing node as an additional response of another existing node — the
         *     concrete "reuse/reconverge" action (no new Dialogue row, just a new edge).
         */
        DialogueLinkIn: {
            /** Target Id */
            target_id: number;
            /**
             * Option Label
             * @default
             */
            option_label: string;
        };
        /**
         * YarnImportOut
         * @description Result of a Yarn import: how much landed, its new root(s), and anything skipped.
         */
        YarnImportOut: {
            /** Created */
            created: number;
            /**
             * Root Ids
             * @default []
             */
            root_ids: number[];
            /**
             * Warnings
             * @default []
             */
            warnings: string[];
        };
        /** YarnImportIn */
        YarnImportIn: {
            /** Text */
            text: string;
            /** Parent Id */
            parent_id?: number | null;
        };
        /** YarnExportOut */
        YarnExportOut: {
            /** Filename */
            filename: string;
            /** Text */
            text: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    api_api_auth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    api_api_get_current_user: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserOut"];
                };
            };
        };
    };
    api_api_update_current_user: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserUpdateIn"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserOut"];
                };
            };
        };
    };
    api_api_list_characters: {
        parameters: {
            query?: {
                project_id?: number | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CharacterOut"][];
                };
            };
        };
    };
    api_api_create_character: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CharacterCreateIn"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CharacterOut"];
                };
            };
        };
    };
    api_api_get_character: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                character_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CharacterDetailOut"];
                };
            };
        };
    };
    api_api_update_character: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                character_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CharacterUpdateIn"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CharacterDetailOut"];
                };
            };
        };
    };
    api_api_add_relationship: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                character_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RelationshipCreateIn"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CharacterDetailOut"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    api_api_delete_relationship: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                character_id: number;
                relationship_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    api_api_upload_character_image: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                character_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": {
                    /**
                     * File
                     * Format: binary
                     */
                    file: string;
                };
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CharacterDetailOut"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    api_api_generate_character_image: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                character_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GenerateImageIn"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CharacterDetailOut"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    api_api_list_entity_types: {
        parameters: {
            query?: {
                project_id?: number | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EntityTypeOut"][];
                };
            };
        };
    };
    api_api_create_entity_type: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EntityTypeCreateIn"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EntityTypeOut"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    api_api_delete_entity_type: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                entity_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    api_api_update_entity_type: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                entity_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EntityTypeUpdateIn"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EntityTypeOut"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    api_api_upload_entity_image: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                entity_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": {
                    /**
                     * File
                     * Format: binary
                     */
                    file: string;
                };
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EntityTypeOut"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    api_api_generate_entity_image: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                entity_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GenerateImageIn"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EntityTypeOut"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    api_api_seed_entities: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EntityTypeOut"][];
                };
            };
        };
    };
    api_api_list_projects: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectOut"][];
                };
            };
        };
    };
    api_api_create_project: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProjectCreateIn"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectOut"];
                };
            };
        };
    };
    api_api_get_project: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectOut"];
                };
            };
        };
    };
    api_api_update_project: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProjectUpdateIn"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectOut"];
                };
            };
        };
    };
    api_api_export_project: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    api_api_list_abilities: {
        parameters: {
            query?: {
                project_id?: number | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AbilityOut"][];
                };
            };
        };
    };
    api_api_create_ability: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AbilityCreateIn"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AbilityOut"];
                };
            };
        };
    };
    api_api_delete_ability: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                ability_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    api_api_update_ability: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                ability_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AbilityUpdateIn"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AbilityOut"];
                };
            };
        };
    };
    api_api_list_levels: {
        parameters: {
            query?: {
                project_id?: number | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LevelOut"][];
                };
            };
        };
    };
    api_api_create_level: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LevelCreateIn"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LevelOut"];
                };
            };
        };
    };
    api_api_get_level: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                level_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LevelOut"];
                };
            };
        };
    };
    api_api_update_level: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                level_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LevelUpdateIn"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LevelOut"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    api_api_level_characters: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                level_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LevelCharacterOut"][];
                };
            };
        };
    };
    api_api_list_scenes: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SceneOut"][];
                };
            };
        };
    };
    api_api_create_scene: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SceneCreateIn"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SceneOut"];
                };
            };
        };
    };
    api_api_update_scene: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                scene_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SceneUpdateIn"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SceneOut"];
                };
            };
        };
    };
    api_api_list_locations: {
        parameters: {
            query?: {
                level_id?: number | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LocationOut"][];
                };
            };
        };
    };
    api_api_create_location: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LocationCreateIn"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LocationOut"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    api_api_get_location: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                location_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LocationOut"];
                };
            };
        };
    };
    api_api_delete_location: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                location_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    api_api_update_location: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                location_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LocationUpdateIn"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LocationOut"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    api_api_add_location_character: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                location_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LocationCharacterIn"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LocationOut"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    api_api_remove_location_character: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                location_id: number;
                character_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LocationOut"];
                };
            };
        };
    };
    api_api_add_location_connection: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                location_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LocationConnectionIn"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LocationOut"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    api_api_delete_location_connection: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                location_id: number;
                connection_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LocationOut"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    api_api_upload_location_image: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                location_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": {
                    /**
                     * File
                     * Format: binary
                     */
                    file: string;
                };
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LocationOut"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    api_api_generate_location_image: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                location_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GenerateImageIn"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LocationOut"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    api_api_scene_dialogue_tree: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                scene_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DialogueNodeOut"][];
                };
            };
        };
    };
    api_api_list_root_dialogues: {
        parameters: {
            query?: {
                scene_id?: number | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DialogueSummaryOut"][];
                };
            };
        };
    };
    api_api_create_dialogue: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DialogueIn"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DialogueDetailOut"];
                };
            };
        };
    };
    api_api_get_dialogue: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                dialogue_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DialogueDetailOut"];
                };
            };
        };
    };
    api_api_update_dialogue: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                dialogue_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DialogueUpdateIn"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DialogueDetailOut"];
                };
            };
        };
    };
    api_api_link_dialogue: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                dialogue_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DialogueLinkIn"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DialogueDetailOut"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    api_api_import_yarn_view: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                scene_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["YarnImportIn"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["YarnImportOut"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    api_api_export_yarn_view: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                scene_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["YarnExportOut"];
                };
            };
        };
    };
}
