/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/auth": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Authenticate the user (placeholder)
         * @description Placeholder for future authentication.
         *
         *     Always returns HTTP 400 and is intentionally NOT called by the frontend yet.
         */
        post: operations["api_api_auth"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/user": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get the current user */
        get: operations["api_api_get_current_user"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update the current user */
        patch: operations["api_api_update_current_user"];
        trace?: never;
    };
    "/api/characters": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List characters
         * @description All characters, or just one project's characters when `project_id` is given.
         */
        get: operations["api_api_list_characters"];
        put?: never;
        /** Create a character */
        post: operations["api_api_create_character"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/characters/{character_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a character */
        get: operations["api_api_get_character"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update a character */
        patch: operations["api_api_update_character"];
        trace?: never;
    };
    "/api/characters/{character_id}/relationships": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Add or update a relationship
         * @description Directed: creates an edge from this character to `other_id`. Shows only on this
         *     character's page. If the same directed edge already exists, its label is updated.
         */
        post: operations["api_api_add_relationship"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/characters/{character_id}/relationships/{relationship_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Remove a relationship */
        delete: operations["api_api_delete_relationship"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/characters/{character_id}/image": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Upload a character portrait
         * @description Upload an image file for the character; stores it in S3 and saves the public URL.
         */
        post: operations["api_api_upload_character_image"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/characters/{character_id}/generate-image": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Generate a character portrait with AI
         * @description Generate a portrait with FLUX (fal.ai), upload it to S3, and save the key on the character.
         */
        post: operations["api_api_generate_character_image"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List projects */
        get: operations["api_api_list_projects"];
        put?: never;
        /** Create a project */
        post: operations["api_api_create_project"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{project_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a project */
        get: operations["api_api_get_project"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Update a project
         * @description Partial update: rename, Settings (dimension/genre), Systems, or Preview (hud_layout).
         */
        patch: operations["api_api_update_project"];
        trace?: never;
    };
    "/api/levels": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List levels
         * @description All levels, or just one project's levels when `project_id` is given.
         */
        get: operations["api_api_list_levels"];
        put?: never;
        /** Create a level */
        post: operations["api_api_create_level"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/levels/{level_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a level */
        get: operations["api_api_get_level"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update a level */
        patch: operations["api_api_update_level"];
        trace?: never;
    };
    "/api/levels/{level_id}/characters": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Characters in a level (deduced from dialogue)
         * @description The level's cast, deduced from which characters speak its dialogue, each with the
         *     lines they speak (across the level's scenes). Ordered by character name.
         */
        get: operations["api_api_level_characters"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/scenes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List scenes */
        get: operations["api_api_list_scenes"];
        put?: never;
        /**
         * Create a scene
         * @description Create a scene in a level (optionally at a location). Order auto-appends within the level.
         */
        post: operations["api_api_create_scene"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/scenes/{scene_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Update a scene
         * @description Partial update: rename, (re)assign to a location, or reorder.
         */
        patch: operations["api_api_update_scene"];
        trace?: never;
    };
    "/api/locations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List locations
         * @description All locations, or just one level's locations when `level_id` is given.
         */
        get: operations["api_api_list_locations"];
        put?: never;
        /** Create a location */
        post: operations["api_api_create_location"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/locations/{location_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a location */
        get: operations["api_api_get_location"];
        put?: never;
        post?: never;
        /** Delete a location */
        delete: operations["api_api_delete_location"];
        options?: never;
        head?: never;
        /** Update a location */
        patch: operations["api_api_update_location"];
        trace?: never;
    };
    "/api/locations/{location_id}/characters": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Place a character at a location */
        post: operations["api_api_add_location_character"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/locations/{location_id}/characters/{character_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Remove a character from a location */
        delete: operations["api_api_remove_location_character"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/scenes/{scene_id}/dialogues": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * All dialogue nodes in a scene (flat, for the tree view)
         * @description Every dialogue node in a scene as a flat list — the frontend builds the graph from
         *     `id`/`parent_ids`. One JOIN (no N+1); each node's character serializes like everywhere else
         *     (presigned image URL via CharacterOut).
         */
        get: operations["api_api_scene_dialogue_tree"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/dialogues": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List root dialogues
         * @description Root dialogues (no incoming edges). Pass `scene_id` to get the roots for one scene.
         */
        get: operations["api_api_list_root_dialogues"];
        put?: never;
        /**
         * Create a dialogue
         * @description Create a dialogue node. Pass `parent_id` to attach it as a response of another node.
         */
        post: operations["api_api_create_dialogue"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/dialogues/{dialogue_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get a dialogue
         * @description A dialogue with its character, immediate responses, and linking parent(s).
         */
        get: operations["api_api_get_dialogue"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Update a dialogue
         * @description Partial update: only the fields present in the request body are changed.
         */
        patch: operations["api_api_update_dialogue"];
        trace?: never;
    };
    "/api/dialogues/{dialogue_id}/link": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Link an existing node as a response (reuse/reconverge)
         * @description Attach an existing node (`target_id`) as an additional response of `dialogue_id`,
         *     without creating a new node — how two branches converge back onto the same node.
         */
        post: operations["api_api_link_dialogue"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/scenes/{scene_id}/import-yarn": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Import a Yarn script into a scene as dialogue nodes
         * @description Parse a bounded subset of Yarn (see `services/yarn_import.py`) and materialize it as
         *     dialogue nodes/edges in this scene. Pass `parent_id` to attach the pasted content as a new
         *     response of that existing node instead of a freestanding root — continuing a branch that's
         *     already there. All-or-nothing: a bad jump target aborts the whole import rather than
         *     leaving orphaned nodes.
         */
        post: operations["api_api_import_yarn_view"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/scenes/{scene_id}/export-yarn": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Export a scene's dialogue graph as a Yarn script */
        get: operations["api_api_export_yarn_view"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Error */
        Error: {
            /** Error */
            error: string;
        };
        /** UserOut */
        UserOut: {
            /** Id */
            id: number;
            /** Name */
            name: string;
            /** Theme */
            theme: string;
        };
        /**
         * UserUpdateIn
         * @description Partial update of the current user (e.g. their selected theme).
         */
        UserUpdateIn: {
            /** Name */
            name?: string | null;
            /** Theme */
            theme?: string | null;
        };
        /** CharacterOut */
        CharacterOut: {
            /** Id */
            id: number;
            /** Name */
            name: string;
            /**
             * Description
             * @default
             */
            description: string;
            /**
             * Image Url
             * @default
             */
            image_url: string;
        };
        /** CharacterCreateIn */
        CharacterCreateIn: {
            /**
             * Name
             * @default New Character
             */
            name: string;
            /**
             * Description
             * @default
             */
            description: string;
            /** Project Id */
            project_id?: number | null;
        };
        /**
         * CharacterDetailOut
         * @description A single character with its description, portrait, and relationships.
         */
        CharacterDetailOut: {
            /** Id */
            id: number;
            /** Name */
            name: string;
            /**
             * Description
             * @default
             */
            description: string;
            /**
             * Image Url
             * @default
             */
            image_url: string;
            /**
             * Image Key
             * @default
             */
            image_key: string;
            /** Project Id */
            project_id?: number | null;
            /**
             * Related
             * @default []
             */
            related: components["schemas"]["RelatedCharacterOut"][];
            /**
             * Traits
             * @default {}
             */
            traits: {
                [key: string]: unknown;
            };
        };
        /**
         * RelatedCharacterOut
         * @description A character related to another, plus the relationship's label and edge id.
         */
        RelatedCharacterOut: {
            /** Relationship Id */
            relationship_id: number;
            /** Id */
            id: number;
            /** Name */
            name: string;
            /** Relationship */
            relationship: string;
        };
        /**
         * CharacterUpdateIn
         * @description Partial update — omitted fields are left unchanged.
         */
        CharacterUpdateIn: {
            /** Name */
            name?: string | null;
            /** Description */
            description?: string | null;
            /** Traits */
            traits?: {
                [key: string]: unknown;
            } | null;
        };
        /** RelationshipCreateIn */
        RelationshipCreateIn: {
            /** Other Id */
            other_id: number;
            /**
             * Relationship
             * @default
             */
            relationship: string;
        };
        /** GenerateImageIn */
        GenerateImageIn: {
            /** Prompt */
            prompt?: string | null;
        };
        /**
         * ProjectOut
         * @description A game project plus its game-wide config (settings/systems/HUD).
         */
        ProjectOut: {
            /** Id */
            id: number;
            /** Name */
            name: string;
            /** Order */
            order: number;
            /** Dimension */
            dimension: string;
            /** Genre */
            genre: string;
            /**
             * Systems
             * @default {}
             */
            systems: {
                [key: string]: unknown;
            };
            /**
             * Hud Layout
             * @default {}
             */
            hud_layout: {
                [key: string]: unknown;
            };
            /**
             * State Schema
             * @default {}
             */
            state_schema: {
                [key: string]: unknown;
            };
            /**
             * Character Traits
             * @default []
             */
            character_traits: {
                [key: string]: unknown;
            }[];
        };
        /** ProjectCreateIn */
        ProjectCreateIn: {
            /**
             * Name
             * @default New Project
             */
            name: string;
            /** Order */
            order?: number | null;
        };
        /**
         * ProjectUpdateIn
         * @description Partial update — omitted fields are left unchanged. One PATCH serves rename,
         *     Settings (dimension/genre), Systems, and Preview (hud_layout) saves.
         */
        ProjectUpdateIn: {
            /** Name */
            name?: string | null;
            /** Order */
            order?: number | null;
            /** Dimension */
            dimension?: string | null;
            /** Genre */
            genre?: string | null;
            /** Systems */
            systems?: {
                [key: string]: unknown;
            } | null;
            /** Hud Layout */
            hud_layout?: {
                [key: string]: unknown;
            } | null;
            /** State Schema */
            state_schema?: {
                [key: string]: unknown;
            } | null;
            /** Character Traits */
            character_traits?: {
                [key: string]: unknown;
            }[] | null;
        };
        /** LevelOut */
        LevelOut: {
            /** Id */
            id: number;
            /** Name */
            name: string;
            /** Order */
            order: number;
            /** Project Id */
            project_id?: number | null;
        };
        /** LevelCreateIn */
        LevelCreateIn: {
            /**
             * Name
             * @default New Level
             */
            name: string;
            /** Order */
            order?: number | null;
            /** Project Id */
            project_id?: number | null;
        };
        /**
         * LevelUpdateIn
         * @description Partial update of a level (e.g. its title).
         */
        LevelUpdateIn: {
            /** Name */
            name?: string | null;
            /** Order */
            order?: number | null;
        };
        /** LevelCharacterLineOut */
        LevelCharacterLineOut: {
            /** Id */
            id: number;
            /** Text */
            text: string;
            /** Scene Id */
            scene_id?: number | null;
            /**
             * Scene Name
             * @default
             */
            scene_name: string;
        };
        /**
         * LevelCharacterOut
         * @description A character appearing in a level (deduced from dialogue), with the lines they speak.
         */
        LevelCharacterOut: {
            /** Id */
            id: number;
            /** Name */
            name: string;
            /**
             * Description
             * @default
             */
            description: string;
            /**
             * Image Url
             * @default
             */
            image_url: string;
            /**
             * Lines
             * @default []
             */
            lines: components["schemas"]["LevelCharacterLineOut"][];
        };
        /** SceneOut */
        SceneOut: {
            /** Id */
            id: number;
            /** Name */
            name: string;
            /** Level Id */
            level_id: number;
            /** Level Name */
            level_name: string;
            /** Location Id */
            location_id?: number | null;
        };
        /** SceneCreateIn */
        SceneCreateIn: {
            /**
             * Name
             * @default New Scene
             */
            name: string;
            /** Level Id */
            level_id: number;
            /** Location Id */
            location_id?: number | null;
            /** Order */
            order?: number | null;
        };
        /**
         * SceneUpdateIn
         * @description Partial update — omitted fields are left unchanged.
         */
        SceneUpdateIn: {
            /** Name */
            name?: string | null;
            /** Location Id */
            location_id?: number | null;
            /** Order */
            order?: number | null;
        };
        /**
         * LocationOut
         * @description A place within a level, plus the characters manually placed there.
         */
        LocationOut: {
            /** Id */
            id: number;
            /** Name */
            name: string;
            /**
             * Description
             * @default
             */
            description: string;
            /** Order */
            order: number;
            /** Level Id */
            level_id: number;
            /**
             * Characters
             * @default []
             */
            characters: components["schemas"]["CharacterOut"][];
        };
        /** LocationCreateIn */
        LocationCreateIn: {
            /**
             * Name
             * @default New Location
             */
            name: string;
            /**
             * Description
             * @default
             */
            description: string;
            /** Order */
            order?: number | null;
            /** Level Id */
            level_id?: number | null;
        };
        /**
         * LocationUpdateIn
         * @description Partial update — omitted fields are left unchanged.
         */
        LocationUpdateIn: {
            /** Name */
            name?: string | null;
            /** Description */
            description?: string | null;
            /** Order */
            order?: number | null;
        };
        /** LocationCharacterIn */
        LocationCharacterIn: {
            /** Character Id */
            character_id: number;
        };
        /**
         * DialogueNodeOut
         * @description A single node in a scene's flat dialogue list — enough to lay out the whole graph.
         */
        DialogueNodeOut: {
            /** Id */
            id: number;
            /** Title */
            title: string;
            /**
             * Parent Ids
             * @default []
             */
            parent_ids: number[];
            /** Text */
            text: string;
            character?: components["schemas"]["CharacterOut"] | null;
            /**
             * Requirements
             * @default []
             */
            requirements: {
                [key: string]: unknown;
            }[];
            /**
             * Effects
             * @default []
             */
            effects: {
                [key: string]: unknown;
            }[];
        };
        /**
         * DialogueSummaryOut
         * @description Lightweight dialogue used for root lists and response cards. `option_label` is the
         *     edge's player-facing choice text (falls back to `text` when the edge has none set).
         */
        DialogueSummaryOut: {
            /** Id */
            id: number;
            /** Title */
            title: string;
            /** Text */
            text: string;
            /**
             * Option Label
             * @default
             */
            option_label: string;
            character?: components["schemas"]["CharacterOut"] | null;
            /**
             * Requirements
             * @default []
             */
            requirements: {
                [key: string]: unknown;
            }[];
            /**
             * Effects
             * @default []
             */
            effects: {
                [key: string]: unknown;
            }[];
        };
        /**
         * DialogueDetailOut
         * @description The current dialogue plus its immediate responses (the wheel) and the node(s) that
         *     link to it (0 = scene root, 1 = normal back-nav, 2+ = picker).
         */
        DialogueDetailOut: {
            /** Id */
            id: number;
            /** Title */
            title: string;
            /** Text */
            text: string;
            /** Scene Id */
            scene_id?: number | null;
            /**
             * Parents
             * @default []
             */
            parents: components["schemas"]["DialogueParentOut"][];
            character?: components["schemas"]["CharacterOut"] | null;
            /**
             * Requirements
             * @default []
             */
            requirements: {
                [key: string]: unknown;
            }[];
            /**
             * Effects
             * @default []
             */
            effects: {
                [key: string]: unknown;
            }[];
            /**
             * Responses
             * @default []
             */
            responses: components["schemas"]["DialogueSummaryOut"][];
        };
        /**
         * DialogueParentOut
         * @description A node that links to the current one — powers the back-navigation picker when a
         *     node is reachable from more than one place.
         */
        DialogueParentOut: {
            /** Id */
            id: number;
            /** Title */
            title: string;
            /** Text */
            text: string;
        };
        /**
         * DialogueIn
         * @description Payload to create a dialogue (optionally as a response of `parent_id`).
         */
        DialogueIn: {
            /** Scene Id */
            scene_id?: number | null;
            /** Parent Id */
            parent_id?: number | null;
            /** Character Id */
            character_id?: number | null;
            /**
             * Text
             * @default
             */
            text: string;
            /** Requirements */
            requirements?: {
                [key: string]: unknown;
            }[] | null;
            /** Effects */
            effects?: {
                [key: string]: unknown;
            }[] | null;
        };
        /**
         * DialogueUpdateIn
         * @description Partial update — omitted fields are left unchanged.
         */
        DialogueUpdateIn: {
            /** Character Id */
            character_id?: number | null;
            /** Text */
            text?: string | null;
            /** Requirements */
            requirements?: {
                [key: string]: unknown;
            }[] | null;
            /** Effects */
            effects?: {
                [key: string]: unknown;
            }[] | null;
        };
        /**
         * DialogueLinkIn
         * @description Attach an existing node as an additional response of another existing node — the
         *     concrete "reuse/reconverge" action (no new Dialogue row, just a new edge).
         */
        DialogueLinkIn: {
            /** Target Id */
            target_id: number;
            /**
             * Option Label
             * @default
             */
            option_label: string;
        };
        /**
         * YarnImportOut
         * @description Result of a Yarn import: how much landed, its new root(s), and anything skipped.
         */
        YarnImportOut: {
            /** Created */
            created: number;
            /**
             * Root Ids
             * @default []
             */
            root_ids: number[];
            /**
             * Warnings
             * @default []
             */
            warnings: string[];
        };
        /** YarnImportIn */
        YarnImportIn: {
            /** Text */
            text: string;
            /** Parent Id */
            parent_id?: number | null;
        };
        /** YarnExportOut */
        YarnExportOut: {
            /** Filename */
            filename: string;
            /** Text */
            text: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    api_api_auth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    api_api_get_current_user: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserOut"];
                };
            };
        };
    };
    api_api_update_current_user: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserUpdateIn"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserOut"];
                };
            };
        };
    };
    api_api_list_characters: {
        parameters: {
            query?: {
                project_id?: number | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CharacterOut"][];
                };
            };
        };
    };
    api_api_create_character: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CharacterCreateIn"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CharacterOut"];
                };
            };
        };
    };
    api_api_get_character: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                character_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CharacterDetailOut"];
                };
            };
        };
    };
    api_api_update_character: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                character_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CharacterUpdateIn"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CharacterDetailOut"];
                };
            };
        };
    };
    api_api_add_relationship: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                character_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RelationshipCreateIn"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CharacterDetailOut"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    api_api_delete_relationship: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                character_id: number;
                relationship_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    api_api_upload_character_image: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                character_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": {
                    /**
                     * File
                     * Format: binary
                     */
                    file: string;
                };
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CharacterDetailOut"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    api_api_generate_character_image: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                character_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GenerateImageIn"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CharacterDetailOut"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    api_api_list_projects: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectOut"][];
                };
            };
        };
    };
    api_api_create_project: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProjectCreateIn"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectOut"];
                };
            };
        };
    };
    api_api_get_project: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectOut"];
                };
            };
        };
    };
    api_api_update_project: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProjectUpdateIn"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectOut"];
                };
            };
        };
    };
    api_api_list_levels: {
        parameters: {
            query?: {
                project_id?: number | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LevelOut"][];
                };
            };
        };
    };
    api_api_create_level: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LevelCreateIn"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LevelOut"];
                };
            };
        };
    };
    api_api_get_level: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                level_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LevelOut"];
                };
            };
        };
    };
    api_api_update_level: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                level_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LevelUpdateIn"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LevelOut"];
                };
            };
        };
    };
    api_api_level_characters: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                level_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LevelCharacterOut"][];
                };
            };
        };
    };
    api_api_list_scenes: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SceneOut"][];
                };
            };
        };
    };
    api_api_create_scene: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SceneCreateIn"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SceneOut"];
                };
            };
        };
    };
    api_api_update_scene: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                scene_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SceneUpdateIn"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SceneOut"];
                };
            };
        };
    };
    api_api_list_locations: {
        parameters: {
            query?: {
                level_id?: number | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LocationOut"][];
                };
            };
        };
    };
    api_api_create_location: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LocationCreateIn"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LocationOut"];
                };
            };
        };
    };
    api_api_get_location: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                location_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LocationOut"];
                };
            };
        };
    };
    api_api_delete_location: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                location_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    api_api_update_location: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                location_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LocationUpdateIn"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LocationOut"];
                };
            };
        };
    };
    api_api_add_location_character: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                location_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LocationCharacterIn"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LocationOut"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    api_api_remove_location_character: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                location_id: number;
                character_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LocationOut"];
                };
            };
        };
    };
    api_api_scene_dialogue_tree: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                scene_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DialogueNodeOut"][];
                };
            };
        };
    };
    api_api_list_root_dialogues: {
        parameters: {
            query?: {
                scene_id?: number | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DialogueSummaryOut"][];
                };
            };
        };
    };
    api_api_create_dialogue: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DialogueIn"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DialogueDetailOut"];
                };
            };
        };
    };
    api_api_get_dialogue: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                dialogue_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DialogueDetailOut"];
                };
            };
        };
    };
    api_api_update_dialogue: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                dialogue_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DialogueUpdateIn"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DialogueDetailOut"];
                };
            };
        };
    };
    api_api_link_dialogue: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                dialogue_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DialogueLinkIn"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DialogueDetailOut"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    api_api_import_yarn_view: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                scene_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["YarnImportIn"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["YarnImportOut"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    api_api_export_yarn_view: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                scene_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["YarnExportOut"];
                };
            };
        };
    };
}
